import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcrypt";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const prisma = new PrismaClient({ adapter });

async function main() {
  const adminRole = await prisma.role.upsert({
    where: { name: "Admin" },
    update: {},
    create: { name: "Admin" },
  });

  const cashierRole = await prisma.role.upsert({
    where: { name: "Cashier" },
    update: {},
    create: { name: "Cashier" },
  });

  const [adminPassword, cashierPassword] = await Promise.all([
    bcrypt.hash("admin123", 10),
    bcrypt.hash("cashier123", 10),
  ]);

  await prisma.user.upsert({
    where: { username: "admin" },
    update: {
      name: "GDC Admin",
      password: adminPassword,
      roleId: adminRole.id,
    },
    create: {
      name: "GDC Admin",
      username: "admin",
      password: adminPassword,
      roleId: adminRole.id,
    },
  });

  const cashierUser = await prisma.user.upsert({
    where: { username: "cashier" },
    update: {
      name: "Juan Dela Cruz",
      password: cashierPassword,
      roleId: cashierRole.id,
    },
    create: {
      name: "Juan Dela Cruz",
      username: "cashier",
      password: cashierPassword,
      roleId: cashierRole.id,
    },
  });

  const shiftStartedAt = new Date();
  shiftStartedAt.setHours(8, 0, 0, 0);

  const existingOpenShift = await prisma.shift.findFirst({
    where: {
      endedAt: null,
      userId: cashierUser.id,
    },
  });

  if (!existingOpenShift) {
    await prisma.shift.create({
      data: {
        openingCash: 2000,
        startedAt: shiftStartedAt,
        userId: cashierUser.id,
      },
    });
  }

// Categories
const categories = await Promise.all([
  prisma.category.upsert({
    where: { name: "Beverages" },
    update: {},
    create: {
      name: "Beverages",
      description: "Soft drinks and bottled drinks",
    },
  }),
  prisma.category.upsert({
    where: { name: "Snacks" },
    update: {},
    create: {
      name: "Snacks",
      description: "Snack foods",
    },
  }),
  prisma.category.upsert({
    where: { name: "Instant Noodles" },
    update: {},
    create: {
      name: "Instant Noodles",
      description: "Instant noodles",
    },
  }),
  prisma.category.upsert({
    where: { name: "Canned Goods" },
    update: {},
    create: {
      name: "Canned Goods",
      description: "Canned food",
    },
  }),
]);


const products = [
  {
    name: "Coca-Cola 330ml",
    barcode: "480001100001",
    description: "Soft Drink",
    price: 25,
    costPrice: 18,
    stock: 100,
    unit: "bottle",
    category: "Beverages",
  },
  {
    name: "Sprite 330ml",
    barcode: "480001100002",
    description: "Soft Drink",
    price: 25,
    costPrice: 18,
    stock: 100,
    unit: "bottle",
    category: "Beverages",
  },
  {
    name: "Royal 330ml",
    barcode: "480001100003",
    description: "Orange Soda",
    price: 25,
    costPrice: 18,
    stock: 100,
    unit: "bottle",
    category: "Beverages",
  },
  {
    name: "Piattos Cheese",
    barcode: "480001200001",
    description: "Potato Chips",
    price: 22,
    costPrice: 15,
    stock: 80,
    unit: "pack",
    category: "Snacks",
  },
  {
    name: "Nova Country Cheddar",
    barcode: "480001200002",
    description: "Corn Snack",
    price: 20,
    costPrice: 13,
    stock: 80,
    unit: "pack",
    category: "Snacks",
  },
  {
    name: "Lucky Me Beef",
    barcode: "480001300001",
    description: "Instant Noodles",
    price: 18,
    costPrice: 12,
    stock: 150,
    unit: "pack",
    category: "Instant Noodles",
  },
  {
    name: "Lucky Me Chicken",
    barcode: "480001300002",
    description: "Instant Noodles",
    price: 18,
    costPrice: 12,
    stock: 150,
    unit: "pack",
    category: "Instant Noodles",
  },
  {
    name: "Century Tuna",
    barcode: "480001400001",
    description: "Canned Tuna",
    price: 42,
    costPrice: 33,
    stock: 70,
    unit: "can",
    category: "Canned Goods",
  },
  {
  name: "Mountain Dew 330ml",
  barcode: "480001100005",
  description: "Soft Drink",
  price: 25,
  costPrice: 18,
  stock: 120,
  unit: "bottle",
  category: "Beverages",
},
{
  name: "Pepsi 330ml",
  barcode: "480001100006",
  description: "Soft Drink",
  price: 25,
  costPrice: 18,
  stock: 120,
  unit: "bottle",
  category: "Beverages",
},
{
  name: "7 Up 330ml",
  barcode: "480001100007",
  description: "Soft Drink",
  price: 25,
  costPrice: 18,
  stock: 100,
  unit: "bottle",
  category: "Beverages",
},
{
  name: "Sting Energy Drink",
  barcode: "480001100008",
  description: "Energy Drink",
  price: 22,
  costPrice: 16,
  stock: 90,
  unit: "bottle",
  category: "Beverages",
},
{
  name: "C2 Apple 355ml",
  barcode: "480001100009",
  description: "Tea Drink",
  price: 20,
  costPrice: 14,
  stock: 100,
  unit: "bottle",
  category: "Beverages",
},
{
  name: "C2 Lemon 355ml",
  barcode: "480001100010",
  description: "Tea Drink",
  price: 20,
  costPrice: 14,
  stock: 100,
  unit: "bottle",
  category: "Beverages",
},
{
  name: "Summit Water 500ml",
  barcode: "480001100011",
  description: "Mineral Water",
  price: 18,
  costPrice: 10,
  stock: 150,
  unit: "bottle",
  category: "Beverages",
},
{
  name: "Gatorade Blue Bolt",
  barcode: "480001100012",
  description: "Sports Drink",
  price: 35,
  costPrice: 28,
  stock: 60,
  unit: "bottle",
  category: "Beverages",
},
{
  name: "VCut BBQ",
  barcode: "480001200004",
  description: "Potato Chips",
  price: 22,
  costPrice: 15,
  stock: 90,
  unit: "pack",
  category: "Snacks",
},
{
  name: "Chippy BBQ",
  barcode: "480001200005",
  description: "Corn Chips",
  price: 20,
  costPrice: 13,
  stock: 80,
  unit: "pack",
  category: "Snacks",
},
{
  name: "Cracklings",
  barcode: "480001200006",
  description: "Corn Snack",
  price: 18,
  costPrice: 12,
  stock: 90,
  unit: "pack",
  category: "Snacks",
},
{
  name: "Clover Chips",
  barcode: "480001200007",
  description: "Corn Chips",
  price: 18,
  costPrice: 12,
  stock: 100,
  unit: "pack",
  category: "Snacks",
},
{
  name: "Oishi Prawn Crackers",
  barcode: "480001200008",
  description: "Prawn Crackers",
  price: 20,
  costPrice: 14,
  stock: 100,
  unit: "pack",
  category: "Snacks",
},
{
  name: "Cheezy Red",
  barcode: "480001200009",
  description: "Cheese Snack",
  price: 20,
  costPrice: 14,
  stock: 90,
  unit: "pack",
  category: "Snacks",
},
{
  name: "Mr. Chips",
  barcode: "480001200010",
  description: "Potato Chips",
  price: 22,
  costPrice: 15,
  stock: 90,
  unit: "pack",
  category: "Snacks",
},
{
  name: "Lucky Me Bulalo",
  barcode: "480001300004",
  description: "Instant Noodles",
  price: 18,
  costPrice: 12,
  stock: 120,
  unit: "pack",
  category: "Instant Noodles",
},
{
  name: "Lucky Me Kalamansi",
  barcode: "480001300005",
  description: "Pancit Canton",
  price: 20,
  costPrice: 14,
  stock: 150,
  unit: "pack",
  category: "Instant Noodles",
},
{
  name: "Lucky Me Chilimansi",
  barcode: "480001300006",
  description: "Pancit Canton",
  price: 20,
  costPrice: 14,
  stock: 150,
  unit: "pack",
  category: "Instant Noodles",
},
{
  name: "Payless Xtra Big Beef",
  barcode: "480001300007",
  description: "Instant Noodles",
  price: 24,
  costPrice: 18,
  stock: 100,
  unit: "pack",
  category: "Instant Noodles",
},
{
  name: "Nissin Ramen Seafood",
  barcode: "480001300008",
  description: "Instant Noodles",
  price: 28,
  costPrice: 20,
  stock: 90,
  unit: "pack",
  category: "Instant Noodles",
},
{
  name: "555 Sardines Tomato",
  barcode: "480001400003",
  description: "Sardines",
  price: 29,
  costPrice: 21,
  stock: 90,
  unit: "can",
  category: "Canned Goods",
},
{
  name: "Argentina Corned Beef",
  barcode: "480001400004",
  description: "Corned Beef",
  price: 49,
  costPrice: 38,
  stock: 70,
  unit: "can",
  category: "Canned Goods",
},
{
  name: "Purefoods Corned Beef",
  barcode: "480001400005",
  description: "Corned Beef",
  price: 58,
  costPrice: 46,
  stock: 60,
  unit: "can",
  category: "Canned Goods",
},
{
  name: "Ligo Sardines",
  barcode: "480001400006",
  description: "Sardines",
  price: 30,
  costPrice: 22,
  stock: 90,
  unit: "can",
  category: "Canned Goods",
},
{
  name: "Spam Classic",
  barcode: "480001400007",
  description: "Luncheon Meat",
  price: 185,
  costPrice: 160,
  stock: 30,
  unit: "can",
  category: "Canned Goods",
},
{
  name: "Kopiko Brown",
  barcode: "480001500003",
  description: "Coffee Mix",
  price: 16,
  costPrice: 11,
  stock: 200,
  unit: "sachet",
  category: "Coffee",
},
{
  name: "San Mig Coffee Original",
  barcode: "480001500004",
  description: "Coffee Mix",
  price: 15,
  costPrice: 10,
  stock: 200,
  unit: "sachet",
  category: "Coffee",
},
{
  name: "Nescafe Creamy White",
  barcode: "480001500005",
  description: "Coffee Mix",
  price: 16,
  costPrice: 11,
  stock: 200,
  unit: "sachet",
  category: "Coffee",
},
{
  name: "Fita Crackers",
  barcode: "480001600003",
  description: "Crackers",
  price: 10,
  costPrice: 7,
  stock: 200,
  unit: "pack",
  category: "Biscuits",
},
{
  name: "Hansel Mocha",
  barcode: "480001600004",
  description: "Biscuits",
  price: 12,
  costPrice: 8,
  stock: 180,
  unit: "pack",
  category: "Biscuits",
},
{
  name: "Rebisco Sandwich",
  barcode: "480001600005",
  description: "Biscuits",
  price: 15,
  costPrice: 10,
  stock: 180,
  unit: "pack",
  category: "Biscuits",
},
{
  name: "Bingo Chocolate",
  barcode: "480001600006",
  description: "Chocolate Cookies",
  price: 15,
  costPrice: 10,
  stock: 180,
  unit: "pack",
  category: "Biscuits",
},
{
  name: "Palmolive Green 180ml",
  barcode: "480001700003",
  description: "Shampoo",
  price: 139,
  costPrice: 115,
  stock: 50,
  unit: "bottle",
  category: "Personal Care",
},
{
  name: "Head & Shoulders Cool Menthol",
  barcode: "480001700004",
  description: "Shampoo",
  price: 8,
  costPrice: 5,
  stock: 300,
  unit: "sachet",
  category: "Personal Care",
},
{
  name: "Closeup Red Hot",
  barcode: "480001700005",
  description: "Toothpaste",
  price: 68,
  costPrice: 54,
  stock: 70,
  unit: "tube",
  category: "Personal Care",
},
{
  name: "Dove White Beauty Bar",
  barcode: "480001700006",
  description: "Soap",
  price: 58,
  costPrice: 45,
  stock: 60,
  unit: "bar",
  category: "Personal Care",
},
{
  name: "Surf Powder 70g",
  barcode: "480001800003",
  description: "Laundry Detergent",
  price: 15,
  costPrice: 10,
  stock: 200,
  unit: "sachet",
  category: "Household",
},
{
  name: "Ariel Powder 66g",
  barcode: "480001800004",
  description: "Laundry Detergent",
  price: 18,
  costPrice: 13,
  stock: 180,
  unit: "sachet",
  category: "Household",
},
{
  name: "Breeze Powder 66g",
  barcode: "480001800005",
  description: "Laundry Detergent",
  price: 17,
  costPrice: 12,
  stock: 180,
  unit: "sachet",
  category: "Household",
},
{
  name: "Zonrox Original 500ml",
  barcode: "480001800006",
  description: "Bleach",
  price: 38,
  costPrice: 29,
  stock: 80,
  unit: "bottle",
  category: "Household",
},
{
  name: "Mr. Muscle Cleaner",
  barcode: "480001800007",
  description: "Multi-purpose Cleaner",
  price: 82,
  costPrice: 65,
  stock: 40,
  unit: "bottle",
  category: "Household",
},
];

for (const product of products) {
  await prisma.product.upsert({
    where: {
      barcode: product.barcode,
    },
    update: {},
create: {
  name: product.name,
  barcode: product.barcode,
  description: product.description,
  price: product.price,
  costPrice: product.costPrice,
  stock: product.stock,
  unit: product.unit,
  category: {
    connect: {
      name: product.category,
    },
  },
},
  });
}

  console.log("Seed completed.");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
